image: gcc
variables:
  GIT_SUBMODULE_STRATEGY: normal
  
stages:
  - build
  - doc

before_script:
  - git status
  - mkdir -p build/
  - cd build/

compile_cpp_api:
  stage: build
  script:
    - cmake ..
    - cmake --build .
    
pages:
  stage: doc
  script:
    - cmake ..
    - cmake --build . --target doc
    - mv doc/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master
    - cmake