image: gcc
variables:
  GIT_SUBMODULE_STRATEGY: normal
  
stages:
  - build
  - doc
  - test

before_script:
  - git status
  - mkdir -p build/
  - cd build/

compile_api:
  stage: build
  script:
    - cmake ..
    - cmake --build .
    - cmake -DCAMEOPYTHON_TESTS=ON ..
    - cmake --build .

test:
  stage: test
  script:
   - cd ..
   - ./test.sh
   
pages:
  stage: doc
  script:
    - cmake ..
    - cmake --build . --target doc
    - mv doc/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master