site_name: CAMEO

theme:
  name: material
  highlightjs: true
  palette:
    primary: orange
  features:
    - content.code.copy
    - navigation.footer
  logo: images/Logo.png
  favicon: images/Logo.png
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - style.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ILLGrenoble/cameo

repo_url: https://github.com/ILLGrenoble/cameo

nav:
  - 'index.md'
  - 'installation.md'
  - 'getting-started.md'
  - 'configure-a-server.md'
  - 'control-the-apps.md'
  - 'make-the-apps-communicate.md'
  - 'app-registration.md'
  - 'synchronization.md'
  - 'track-the-app-failures.md'
  - 'use-the-proxies-with-a-firewall.md'
  - 'exceptions.md'
  - 'examples.md'
  - 'APIs.md'
  - 'developments.md'